name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
website: ${project.url}

api-version: ${bukkitApiVersion}
main: ${mainClass}

commands:
  worldrescue:
    description: Manage your backups.
    usage: /worldrescue <command>
    aliases: ["wr"]
