name: WorldRebuild
version: ${project.version}
description: ${project.description}
author: tobynextdoor

main: de.tobynextdoor.WorldRebuild.WorldRebuild

commands:
    worldrebuild:
      description: Manage your backups.
      usage: /worldrebuild <command>
    wr:
      description: Manage your backups.
      usage: /wr <command>
