name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
website: ${project.url}

api-version: ${apiVersion}
main: ${mainClass}

commands:
    worldrebuild:
      description: Manage your backups.
      usage: /worldrebuild <command>
    wr:
      description: Manage your backups.
      usage: /wr <command>
